FROM arm64v8/openjdk:8-jdk-buster

WORKDIR /usr

# add a non root user
RUN useradd -m elasticuser

# Download
RUN apt update
RUN apt install -y curl nano

RUN curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.23.tar.gz

# unarchive
RUN tar -xvf elasticsearch-6.8.23.tar.gz

ADD elasticsearch.yml /usr/elasticsearch-6.8.23/config/elasticsearch.yml

RUN chown -R elasticuser: .
USER elasticuser

ENV JAVA_HOME=/usr/local/openjdk-18/bin/java
ENV xpack.security.enabled=false
ENV discovery.type=single-node

ENV xpack.security.enabled: false
ENV xpack.ml.enabled: false

# run
RUN cd elasticsearch-6.8.23/bin
RUN chown -R elasticuser: elasticsearch-6.8.23

EXPOSE 9200 9300
CMD cd /usr/elasticsearch-6.8.23/bin/ && ./elasticsearch
